### ISSUE TITLE
Type manager changes between 1.3.8 and 1.3.5

### ISSUE THREAD

**Issue by SAMYTHEBIGJUICY** [needle-mirror/com.unity.entities#2]
More of an enquiry really but was anything changed between the versions that might cause type manager issues? I had serious errors in 1.3.8 and third party packages that depend on Entities like Obi rope and A*. Reverting to 1.3.5 solved everything for me. The error prints I was getting were: 

InvalidOperationException: ComponentType.TypeIndex does not match precalculated index for Pathfinding.ECS.MovementSettings. Expected: 00002000 Actual: 00000000
Unity.Entities.TypeManager.AddAllComponentTypes (System.Type[] componentTypes, System.Int32 startTypeIndex, System.Collections.Generic.Dictionary2[TKey,TValue] writeGroupByType, System.Collections.Generic.Dictionary2[TKey,TValue] descendantCountByType) (at ./Library/PackageCache/com.unity.entities@1.3.8/Unity.Entities/Types/TypeManager.cs:2800)
UnityEngine.Debug:LogException(Exception)
Unity.Debug:LogException(Exception) (at ./Library/PackageCache/com.unity.entities@1.3.8/Unity.Entities/Stubs/Unity/Debug.cs:17)
Unity.Entities.TypeManager:AddAllComponentTypes(Type[], Int32, Dictionary2, Dictionary2) (at ./Library/PackageCache/com.unity.entities@1.3.8/Unity.Entities/Types/TypeManager.cs:2818)
Unity.Entities.TypeManager:InitializeAllComponentTypes() (at ./Library/PackageCache/com.unity.entities@1.3.8/Unity.Entities/Types/TypeManager.cs:2674)
Unity.Entities.TypeManager:Initialize() (at ./Library/PackageCache/com.unity.entities@1.3.8/Unity.Entities/Types/TypeManager.cs:1528)
Unity.Entities.AttachToEntityClonerInjection:Initialize() (at ./Library/PackageCache/com.unity.entities@1.3.8/Unity.Entities.Hybrid/Injection/CompanionGameObject.cs:23)
Unity.Entities.AttachToEntityClonerInjection:.cctor() (at ./Library/PackageCache/com.unity.entities@1.3.8/Unity.Entities.Hybrid/Injection/CompanionGameObject.cs:17)
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes(Type[])

**Comment by marwie** [comment]
Hi please report issues through the official Unity Bugreport Channels - we are not directly affiliated with Unity so unfortunately opening issues here wont reach the devs

**Comment by SAMYTHEBIGJUICY** [comment]
Gotcha
